language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
  - python: '2.7'

# command to install dependencies
install:
  - pip install pylint
  - pip install -r requirements.txt

before_script:
  - chmod +x utility_container.py

# command to run tests
script:
  - pylint --exit-zero utility_container.py
  - pip list
  - ./utility_container.py --help