language: python
dist: xenial

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"

apt_packages:
  - pylint

virtualenv:
  system_site_packages: true

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - chmod +x utility-container.py
  - pylint utility-container.py

# command to run tests
script:
  - ./utility-container.py